//! Help rendering data model. Ported from the donor `src/help/model.rs`
//! (retired tree).
//!
//! One deliberate omission versus the donor: the `HelpExtras::live_examples_fn`
//! hook is dropped. Live examples were generated by opening the vault cache and
//! running a query; the phase-1 rewrite has no query core, and — empirically —
//! the donor's own `--help` opens a freshly-created (empty) cache, so its
//! live-examples generator finds zero documents and emits nothing under the
//! parity harness. The block therefore never renders on either side, so the
//! generator hook is future work (returns when the query core ports), not a
//! current divergence. `HelpModel::live_examples` stays and is always empty.

/// Which form of help is being rendered.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum HelpForm {
    /// `-h` — orient. Fits a screen. One-line descriptions.
    Short,
    /// `--help` — teach. Multi-page. Per-flag prose where it earns it.
    Long,
}

/// A single flag or option entry.
#[derive(Debug, Clone)]
pub struct FlagEntry {
    /// Short flag like `-h`. `None` if the arg has only a long form.
    pub short: Option<char>,
    /// Long flag like `--text`. `None` if the arg has only a short form.
    pub long: Option<String>,
    /// Value placeholder like `<NEEDLE>` or `<FIELD:VALUE>`. `None` if the
    /// flag takes no value (e.g. `--all`).
    pub value_name: Option<String>,
    /// One-line description (shown in `-h` and as the lead line in `--help`).
    pub short_desc: String,
    /// Optional multi-paragraph prose. Rendered only in `--help`. `None`
    /// means the short description is the only text.
    pub long_desc: Option<String>,
    /// Possible enum values like `["json", "jsonl", "table"]`. Empty for
    /// free-form args. Shown in `--help` (long form) only.
    pub possible_values: Vec<String>,
}

/// A named group of flags, e.g. "Filter options", "Triage filters".
#[derive(Debug, Clone)]
pub struct FlagGroup {
    /// Display heading. Always rendered uppercase + dim bold by the renderer.
    pub heading: String,
    /// Flags in this group, in clap declaration order.
    pub flags: Vec<FlagEntry>,
}

/// A global option. Globals render in one block (no collapse) with one line
/// each. `-h` shows [`short_desc`](Self::short_desc) (clamped to the spec's
/// ≤70-char column); `--help` shows [`long_desc`](Self::long_desc) unclamped
/// when present, so a global whose full description exceeds the column is not
/// silently truncated in long help (NRN-335).
#[derive(Debug, Clone)]
pub struct GlobalEntry {
    pub short: Option<char>,
    pub long: Option<String>,
    /// `None` if the global takes no value (e.g. `--verbose`).
    pub value_name: Option<String>,
    /// The concise one-line description shown in `-h`. Constrained to ≤70 chars
    /// per the help-output v2 spec §2.2 (clamped by the renderer as a backstop).
    pub short_desc: String,
    /// The full description shown UNCLAMPED in `--help` (from clap `long_help`).
    /// `None` — the common case — falls back to `short_desc`. Populated only in
    /// the long form (see the extractor), so `-h` always renders `short_desc`.
    pub long_desc: Option<String>,
}

/// A single generated, runnable example for the LIVE EXAMPLES block in
/// `--help`. Retained for the renderer + its tests; never materialized by the
/// phase-1 rewrite (no query core), so the block never renders in practice.
#[derive(Debug, Clone)]
pub struct LiveExample {
    /// Full command line including the binary name, e.g.
    /// `"norn find --eq type:note --sort modified --limit 5"`. The renderer
    /// tokenizes this for per-token coloring; no trailing whitespace.
    pub query: String,
    /// Confirmed non-zero match count. Rendered as the tail
    /// `"{match_count} documents match"`.
    pub match_count: usize,
}

/// Phase-deferred extras: canned examples and conceptual sections.
#[derive(Debug, Clone, Default)]
pub struct HelpExtras {
    /// `Vec<(command_str, comment_str)>`.
    pub canned_examples: Vec<(String, String)>,
    /// `Vec<(heading, body)>`.
    pub conceptual_sections: Vec<(String, String)>,
}

/// Complete rendering input for one help invocation.
#[derive(Debug, Clone)]
pub struct HelpModel {
    /// e.g. `"norn"`, `"norn find"`, `"norn cache index"`.
    pub command_path: String,
    /// One-line description (from clap `about`).
    pub about: String,
    /// Optional multi-line description (from clap `long_about`). Rendered
    /// only in `--help`.
    pub long_about: Option<String>,
    /// Positional arguments, in declaration order.
    pub positionals: Vec<FlagEntry>,
    /// Flag groups in display order (NOT clap declaration order). The
    /// extractor groups by `help_heading` and orders groups by first-seen.
    pub groups: Vec<FlagGroup>,
    /// Global options. Always rendered as one block after groups.
    pub globals: Vec<GlobalEntry>,
    /// Subcommand list for parent commands. Empty for leaf commands.
    pub subcommands: Vec<(String, String)>, // (name, about)
    pub extras: HelpExtras,
    /// Materialized live examples for this render. Always empty in the
    /// phase-1 rewrite; the renderer suppresses the block when empty.
    pub live_examples: Vec<LiveExample>,
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn flag_entry_with_short_and_value() {
        let e = FlagEntry {
            short: Some('h'),
            long: Some("help".to_string()),
            value_name: None,
            short_desc: "Print help".to_string(),
            long_desc: None,
            possible_values: vec![],
        };
        assert_eq!(e.short, Some('h'));
        assert_eq!(e.long.as_deref(), Some("help"));
    }

    #[test]
    fn extras_default_is_empty() {
        let x = HelpExtras::default();
        assert!(x.canned_examples.is_empty());
        assert!(x.conceptual_sections.is_empty());
    }

    #[test]
    fn help_form_distinguishes_short_and_long() {
        assert_ne!(HelpForm::Short, HelpForm::Long);
    }

    #[test]
    fn live_example_holds_query_and_count() {
        let e = LiveExample {
            query: "norn find --eq type:note --limit 5".to_string(),
            match_count: 412,
        };
        assert_eq!(e.match_count, 412);
        assert!(e.query.contains("--eq"));
    }
}
